version: '3.7'
name: olp_frontend

services:
  olp_frontend:
    container_name: olp_frontend
    image: nadegamra.azurecr.io/olp_frontend:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 80:80
      - 443:443
